apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user-batman
spec:
  profile:
    # Intentional no displayName for testing
    email: user-batman@opentlc.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [group-batman]